### ISSUE TITLE
任意のユーザーや投稿を削除出来てしまう

### ISSUE THREAD

**Issue by kachick** [kuromitsu0104/gadget-app#67]
セキュリティホールの話ですが、習作アプリだと思うのでpublicに書かせていただきます。
現状サーバーサイドバリデーションが無い様で、curl 等使ってリクエストを送ると好き放題出来てしまうようでした。

<img width="1171" alt="スクリーンショット 2021-02-14 14 11 44" src="https://user-images.githubusercontent.com/1180335/107869298-fb664000-6ecf-11eb-99e1-0cef0f185232.png">
<img width="1178" alt="スクリーンショット 2021-02-14 14 12 18" src="https://user-images.githubusercontent.com/1180335/107869300-fe613080-6ecf-11eb-8adb-979ce4136278.png">

users.2 の 最新投稿を一件消したところ 

<img width="1241" alt="スクリーンショット 2021-02-14 14 21 03" src="https://user-images.githubusercontent.com/1180335/107869301-ff925d80-6ecf-11eb-80f9-81681a83b0ac.png">

users.2 自体を消したところ 

大事なデータだったらすみません 🙇 本格的に運用されだしてから発覚するよりマシかなと思い試させてもらいました。

**Comment by kuromitsu0104** [comment]
ご連絡頂きましてありがとうございます！お返事が遅くなりまして申し訳ないです...。
■対策につきまして
FirebaseAuthから取得したトークンをデコードして得られる uid（各ユーザーで一意なもの）が取得できるので、それを使ってアクション実行前に検証を挟んで対処しようと思います。

1. Vuexストアに uid を保存（既に実装済み）
2. 検証が必要なアクション（create, destroy, update）には params: uid も添付するように変更
3. Rails側のUserモデルに保存された uidカラム の値と params: uid を比較検証
4. 同一uid の場合は、正規ログインユーザーからのリクエストとみなしてアクションを実行

**Comment by kuromitsu0104** [comment]
取り急ぎ Userモデル についてのバリデーションを実装しました。
その他のモデルにつきましても順次進めていきます。

**Comment by kachick** [comment]
https://github.com/kuromitsu0104/gadget-app/pull/68/files#diff-f23c41ccfaa3af742bbdef94c2e8e8dffcf74b7beb63919243987084e894cc59R94 こことか `=` になってますが `==` でなくて大丈夫ですか？

https://github.com/kuromitsu0104/gadget-app/issues/67#issuecomment-779865792, https://github.com/kuromitsu0104/gadget-app/pull/68 と 改修後のサイトを少し拝見させて頂いたのですが、 とりあえず uid を隠しきれていないようです

例えば `curl 'https://gadget-community.com:3000/v1/users/1' | jq .` を叩くと、ゲストユーザーがフォローしているユーザーの一覧があり、そのレスポンスにuidが含まれています。
それを使って `curl 'https://gadget-community.com:3000/v1/users/3' -X DELETE --data 'uid=zjQvrbdUGZTy7UuFAAwp1OF3I8y1'` このように叩くことで

<img width="1189" alt="スクリーンショット 2021-02-17 3 11 21" src="https://user-images.githubusercontent.com/1180335/108104396-9af12180-70ce-11eb-8cf6-cf095bac70f7.png">
<img width="1054" alt="スクリーンショット 2021-02-17 3 14 02" src="https://user-images.githubusercontent.com/1180335/108104409-9dec1200-70ce-11eb-972f-5f92aaee1b26.png">

この様に、自分はログインすらせずに他人のアカウントを消せてしまいました。
そもそも firebase の uid というのはそれ自体がセキュアな物ではなく、単にIDのようです。
ランダムな文字列が生成されるようなのでうまく隠蔽しきればある程度は対策になるかもしれませんが、根本対処としてはサーバーサイドからfirebaseへ問い合わせに行くstepが必要なのでは無いだろうか？と思いました。
https://github.com/nizi24/PolPa-api/issues/21#issuecomment-779154586 の方が似た問題に妥当そうな方法を考えられていたので、参考にされると良いかもなと思いました。

**Comment by kuromitsu0104** [comment]
こちらの返信に気がつかず申し訳ないです😅
具体的な解決案まで教えてくださりありがとうございます！

今回は『サーバーサイドへの実装』は保留しようと考えております。
理由としては、
1. すでにUID隠蔽の方針で作業進めていたこと。
2. 就活に時間が取られており大幅改修にかける時間がないこと。
3. ポートフォリオを停止させるような改修を避けたいこと。

なので、就活が落ち着いて時間が取れた際には『認証ロジックの大幅改修』に挑戦してみたいと思います！

**Comment by kachick** [comment]
はい、 就活頑張って下さい！ 😄
